name: gpu_image_example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_gpu:
    sdk: flutter
  vector_math: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gpu_shaders: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/